root = "."
tmp_dir = "/tmp"

[build]
cmd = "go build -o ./tmp/main ./src/*.go"
bin = "./tmp/main"

include_ext = ["go", "env"]
include_dir = ["src"]
include_file = [".env"]
exclude_dir = ["../tmp", "vendor"]