name: Generate Swagger docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  swaggo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Install swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Run swag init
        run: swag init -g src/*.go -o ./docs

      - name: Commit and push swagger docs if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add docs
            git commit -m "Update swagger docs"
            git push
          else
            echo "No changes to commit"
          fi
